[project]
name = "explore_image_analysis"
version = "0.1.0"
description = "Explore various ML algorithms applied to images (CNNs, VAEs, Diffussion, etc.)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
